### ISSUE TITLE
Use Open Graph Tags

### ISSUE THREAD

**Issue by pavio** [BSidesRDU/website#10]
Please adjust bsidesrdu website as per:
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fbsidesrdu.org

For the og:image let's use Reneaue's latest t-shirt design...

Or give me owner access as well and I will take care of it...

**Comment by santosomar** [comment]
Just edited the description and title via https://github.com/BSidesRDU/website/commit/5a9a23ad2f38e312098ec33fe855c185ca65f52b

Adding the og:image as a separate commit.

**Comment by santosomar** [comment]
Addressed all the pending items and the website LinkedIn Post Inspector now displays a summary
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fbsidesrdu.org
