### ISSUE TITLE
Please include the schedule

### ISSUE THREAD

**Issue by unregistered436** [BSidesRDU/website#15]
Sessionize has the following code that can be embedded in the site. Please include the smart grid view, and provide a link to navigate to this section / div of the site so we can tweet it.
<script type="text/javascript" src="https://sessionize.com/api/v2/wlmc0rih/view/gridsmart"></script>

If there's a good spot, also please include the speakers wall view somewhere...
<script type="text/javascript" src="https://sessionize.com/api/v2/wlmc0rih/view/sessions"></script>

**Comment by santosomar** [comment]
Just added the schedule. For some reason the second javascript breaks the page. I will troubleshoot a bit later tonight and will leave this issue open until I fix the speaker wall.

**Comment by santosomar** [comment]
The new site looks good now ;-) > > https://bsidesrdu.org/
