### ISSUE TITLE
Update website with 2019 sponsor logos

### ISSUE THREAD

**Issue by ggoddard** [BSidesRDU/website#17]
Sponsor list is as follows:

Avalara
Booz
Cisco
Guidepoint
RSA
SecureWorks
TrendMicro
Valiant
Veracode
ZScaler

Logos can be found on Google Drive in the Sponsorships/Logos directory.

**Comment by santosomar** [comment]
Added the BSIDES RDU 2019 Sponsors via https://github.com/BSidesRDU/website/commit/758cb90ef5e9840883e4d48c9e609d92668ec3a7
