### ISSUE TITLE
Please add Eversec CTF to side events (with logo)

### ISSUE THREAD

**Issue by unregistered436** [BSidesRDU/website#20]
I've attached the Eversec CTF logo in two formats - please use whatever works for you..

![eversec_logo_2](https://user-images.githubusercontent.com/7327282/65709621-3eb3da80-e05f-11e9-88d1-6b355374ed51.png)
![eversec_logo_1_v1 1](https://user-images.githubusercontent.com/7327282/65709622-3eb3da80-e05f-11e9-9ff1-e7503705abde.png)

**Comment by santosomar** [comment]
This issue was for the 2019 event, but forgot to close it.
