### ISSUE TITLE
Unwanted text at bottom of website

### ISSUE THREAD

**Issue by ggoddard** [BSidesRDU/website#6]
@ggoddard @santosomar the bottom of the "about" section of our website still has some lorem ipsum text = "Distinctively benchmark client-focused opportunities vis-a-vis 24/365 relationships. Progressively revolutionize equity invested synergy whereas emerging web services."

**Comment by santosomar** [comment]
Corrected via https://github.com/BSidesRDU/website/commit/ce1b02493b54009a7853056b1ab85494c94df64b 

thanks @ggoddard !!!
