### ISSUE TITLE
Add ticket information to site

### ISSUE THREAD

**Issue by pavio** [BSidesRDU/website#7]
Either add the below link:
http://bsidesrdu2018.eventzilla.net

Or add the following button widget:
<link href="https://d2poexpdc5y9vj.cloudfront.net/public/css/eventzilla-widget-button.css" rel="stylesheet" />  <a id="btnpreview" class="ezilla-widget-button ezilla-red ewb-large" href="http://bsidesrdu.org">Register Now</a>

or the following bigger widget:
<div id="eventzilla-iframe"></div><script type='text/javascript' src='https://d2poexpdc5y9vj.cloudfront.net/public/js/eventzilla-embedd.js?eventid=2138717833'></script>

or this:

<div id="eventzilla-iframe"></div><script type='text/javascript'>window.onload = function() {var iframe = document.createElement('iframe');iframe.id="ifeventzilla";iframe.style.width = "100%";iframe.style.height = "100%";iframe.frameBorder="0";iframe.src = "http://bsidesrdu.org/web/event_embedd.aspx?eventid=2138717833";var evntzilladiv=document.getElementById('eventzilla-iframe');evntzilladiv.appendChild(iframe);};</script>

**Comment by santosomar** [comment]
Added ticket information to the website via 8241783.
