### ISSUE TITLE
Please post the high-level schedule

### ISSUE THREAD

**Issue by unregistered436** [BSidesRDU/website#8]
High level schedule is available now, and I'd like to post it so potential attendees can see it. I've got a couple other abstracts to nail down, so I'll provide an update later with the FULL details.

Time	Presenter	Talk Name
8:00 start	Staff	        Registration
8:30-8:45	Staff	        Welcome & Opening Remarks
8:45-9:45	Shahid Buttar	Keynote from Shahid Buttar, EFF Director Of Grassroots Advocacy 
9:45-10:30	Matt	Approaching Parity: Considerations for adapting enterprise monitoring and incident response (IR) capabilities for efficacy in cloud environments, and how to operationalize these capabilities with a playbook.
10:30-11:15	SleepZ3R0 and HA12TL3Y	Movement After Initial Compromise
11:15-11:30	Staff	      Break!
11:30-12:30	Joel Lathrop	Our Docker app got hacked. Now what?
12:30-2:00	Staff	    Lunch - Food Truck Rodeo!
2:00-2:30	Eric Waters	Security Automation for the Blue Team
3:15-4:15	Matt Martin & Panel Guests	You Can't Dial 911
4:15-4:30	Staff	     Break!
4:30-5:30	@aarondlancaster	Sky-high IR - IR at Cloud Scale
5:30-6:00	Sam Granger	When it rains it pours
6:00-6:45 Neal Humphrey   Rise of the Advisor
6:45-8:30     Staff     Hacker Jeopardy & Social

Please indicate that detailed abstracts will be coming SOON.

**Comment by santosomar** [comment]
ACK... Adding schedule to the website and working on formatting.

**Comment by santosomar** [comment]
Complete schedule has been updated, along with Abstracts and Bios.
